const SINGLE_5S_HIGH_SCORE_STORAGE_KEY = 'single5SHighScore'
const SINGLE_10S_HIGH_SCORE_STORAGE_KEY = 'single10SHighScore'
const FRENETICO_HIGH_SCORE_STORAGE_KEY = 'freneticoHighScore'

export {
    SINGLE_5S_HIGH_SCORE_STORAGE_KEY,
    SINGLE_10S_HIGH_SCORE_STORAGE_KEY,
    FRENETICO_HIGH_SCORE_STORAGE_KEY
}